// <auto-generated />
using CyberTutorial.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CyberTutorial.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AnswerQuestion", b =>
                {
                    b.Property<string>("AnswersAnswerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuestionsQuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("AnswersAnswerId", "QuestionsQuestionId");

                    b.HasIndex("QuestionsQuestionId");

                    b.ToTable("AnswerQuestion");
                });

            modelBuilder.Entity("CourseEmployee", b =>
                {
                    b.Property<string>("CoursesCourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmployeesEmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CoursesCourseId", "EmployeesEmployeeId");

                    b.HasIndex("EmployeesEmployeeId");

                    b.ToTable("CourseEmployee");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.Administrator", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.Answer", b =>
                {
                    b.Property<string>("AnswerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.HasKey("AnswerId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.Attempt", b =>
                {
                    b.Property<string>("AttemptId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsStarted")
                        .HasColumnType("bit");

                    b.Property<string>("QuizId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("StartedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCorrectAnswers")
                        .HasColumnType("int");

                    b.Property<int>("TotalIncorectAnswers")
                        .HasColumnType("int");

                    b.HasKey("AttemptId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("QuizId");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.Company", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerEmiratesId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.CompanySession", b =>
                {
                    b.Property<string>("CompanySessionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TimeCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanySessionId");

                    b.ToTable("CompanySessions");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.Course", b =>
                {
                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            CourseId = "ddec3205-e85f-4b75-a277-ce3db9f4dd6d",
                            CourseDescription = "A collection of procedures and technology designed to address external and internal threats to business security.",
                            CourseImage = "https://localhost:7196/api/Document/Download?documentId=83017331-5426-47f9-ac19-31aaef08bea7",
                            CourseName = "Cloud Security",
                            CourseUrl = "https://localhost:7196/api/Document/Download?documentId=c723b5e9-9971-467f-ac32-88beda990cbf"
                        },
                        new
                        {
                            CourseId = "2cd7a7d7-054b-4fad-8ae6-2310ca92d609",
                            CourseDescription = "A document that you should ideally give to each employee upon hiring. Prospective employees should read the policy, sign it, and date it before they start work.",
                            CourseImage = "https://localhost:7196/api/Document/Download?documentId=83017331-5426-47f9-ac19-31aaef08bea7",
                            CourseName = "Email And Internet Usage Policy",
                            CourseUrl = "https://localhost:7196/api/Document/Download?documentId=342c4724-0aeb-4d69-ba8f-12424e49274a"
                        },
                        new
                        {
                            CourseId = "42ef5e92-3da4-48f6-8d13-6da0326a3e58",
                            CourseDescription = "You'll learn about mobile security vulnerabilities and threats in this in-depth exploration of mobile security in the company.",
                            CourseImage = "https://localhost:7196/api/Document/Download?documentId=83017331-5426-47f9-ac19-31aaef08bea7",
                            CourseName = "Mobile Device Security",
                            CourseUrl = "https://localhost:7196/api/Document/Download?documentId=44fd3336-21d9-4bf7-8b6a-c85d1a4082ef"
                        },
                        new
                        {
                            CourseId = "b8623275-c5cd-4f27-bdbb-75b9d9fb5b84",
                            CourseDescription = "Fake communications that appear to come froma trusted source, but these communications can put all kinds of your data at risk.",
                            CourseImage = "https://localhost:7196/api/Document/Download?documentId=83017331-5426-47f9-ac19-31aaef08bea7",
                            CourseName = "Phishing Attacks",
                            CourseUrl = "https://localhost:7196/api/Document/Download?documentId=15098b99-f2c0-42a9-9cd0-499a4ba0875d"
                        },
                        new
                        {
                            CourseId = "4ff39251-8cc2-4819-8b30-7fe544f8bd08",
                            CourseDescription = "describes measures designed to ensure the physical protection of IT assets such as facilities, equipment and other property from damage and unauthorized physical access.",
                            CourseImage = "https://localhost:7196/api/Document/Download?documentId=83017331-5426-47f9-ac19-31aaef08bea7",
                            CourseName = "Physical Security",
                            CourseUrl = "https://localhost:7196/api/Document/Download?documentId=f4b013a6-b2dd-415c-91f7-54c4b49f5de7"
                        },
                        new
                        {
                            CourseId = "de88a0ef-cd13-4179-a181-18c1d3bdff99",
                            CourseDescription = "Found in popular public places like airports, coffee shops, malls, restaurants, and hotels and it allows you to access the internet for free.",
                            CourseImage = "https://localhost:7196/api/Document/Download?documentId=83017331-5426-47f9-ac19-31aaef08bea7",
                            CourseName = "Public Wi-Fi",
                            CourseUrl = "https://localhost:7196/api/Document/Download?documentId=b97f6cf2-cf17-4abe-9b1c-c4a862701bf8"
                        },
                        new
                        {
                            CourseId = "8d97ee89-cb8b-47ea-b59e-ac276866fe4e",
                            CourseDescription = "A manipulation technique that exploits human error to gain private information, access, or valuables.",
                            CourseImage = "https://localhost:7196/api/Document/Download?documentId=83017331-5426-47f9-ac19-31aaef08bea7",
                            CourseName = "Social Engineering",
                            CourseUrl = "https://localhost:7196/api/Document/Download?documentId=4451fdbd-d680-4633-b552-6a746aa8cc9c"
                        });
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.Document", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DocumentExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DocumentSize")
                        .HasColumnType("bigint");

                    b.Property<string>("DocumentType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.EmployeeDashboard", b =>
                {
                    b.Property<string>("EmployeeDashboardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalCourses")
                        .HasColumnType("int");

                    b.Property<string>("TotalCoursesLastModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalFailed")
                        .HasColumnType("int");

                    b.Property<string>("TotalFailedLastModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPassed")
                        .HasColumnType("int");

                    b.Property<string>("TotalPassedLastModified")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalQuizzes")
                        .HasColumnType("int");

                    b.Property<string>("TotalQuizzesLastModified")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeDashboardId");

                    b.ToTable("EmployeeDashboards");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.EmployeeSession", b =>
                {
                    b.Property<string>("EmployeeSessionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExpiryDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TimeCreated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeSessionId");

                    b.ToTable("EmployeeSessions");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.Question", b =>
                {
                    b.Property<string>("QuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.Quiz", b =>
                {
                    b.Property<string>("QuizId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CourseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximumScore")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("QuizId");

                    b.HasIndex("CourseId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.TopEmployee", b =>
                {
                    b.Property<string>("TopEmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AverageScore")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalQuizzes")
                        .HasColumnType("int");

                    b.HasKey("TopEmployeeId");

                    b.ToTable("TopEmployees");
                });

            modelBuilder.Entity("QuestionQuiz", b =>
                {
                    b.Property<string>("QuestionsQuestionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("QuizzesQuizId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("QuestionsQuestionId", "QuizzesQuizId");

                    b.HasIndex("QuizzesQuizId");

                    b.ToTable("QuestionQuiz");
                });

            modelBuilder.Entity("AnswerQuestion", b =>
                {
                    b.HasOne("CyberTutorial.Domain.Entities.Answer", null)
                        .WithMany()
                        .HasForeignKey("AnswersAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CyberTutorial.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseEmployee", b =>
                {
                    b.HasOne("CyberTutorial.Domain.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CyberTutorial.Domain.Entities.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.Attempt", b =>
                {
                    b.HasOne("CyberTutorial.Domain.Entities.Employee", "Employee")
                        .WithMany("Attempts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CyberTutorial.Domain.Entities.Quiz", "Quiz")
                        .WithMany("Attempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.CompanySession", b =>
                {
                    b.HasOne("CyberTutorial.Domain.Entities.Company", "Company")
                        .WithOne("Session")
                        .HasForeignKey("CyberTutorial.Domain.Entities.CompanySession", "CompanySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.Employee", b =>
                {
                    b.HasOne("CyberTutorial.Domain.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.EmployeeDashboard", b =>
                {
                    b.HasOne("CyberTutorial.Domain.Entities.Employee", "Employee")
                        .WithOne("EmployeeDashboard")
                        .HasForeignKey("CyberTutorial.Domain.Entities.EmployeeDashboard", "EmployeeDashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.EmployeeSession", b =>
                {
                    b.HasOne("CyberTutorial.Domain.Entities.Employee", "Employee")
                        .WithOne("Session")
                        .HasForeignKey("CyberTutorial.Domain.Entities.EmployeeSession", "EmployeeSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.Quiz", b =>
                {
                    b.HasOne("CyberTutorial.Domain.Entities.Course", "Course")
                        .WithMany("Quizzes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.TopEmployee", b =>
                {
                    b.HasOne("CyberTutorial.Domain.Entities.Employee", "Employee")
                        .WithOne("TopEmployee")
                        .HasForeignKey("CyberTutorial.Domain.Entities.TopEmployee", "TopEmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("QuestionQuiz", b =>
                {
                    b.HasOne("CyberTutorial.Domain.Entities.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CyberTutorial.Domain.Entities.Quiz", null)
                        .WithMany()
                        .HasForeignKey("QuizzesQuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.Company", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.Course", b =>
                {
                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("EmployeeDashboard");

                    b.Navigation("Session");

                    b.Navigation("TopEmployee");
                });

            modelBuilder.Entity("CyberTutorial.Domain.Entities.Quiz", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
